// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	moderators "disspace/business/moderators"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByCategoryID provides a mock function with given fields: ctx, idCategory
func (_m *Repository) GetByCategoryID(ctx context.Context, idCategory string) ([]moderators.Domain, error) {
	ret := _m.Called(ctx, idCategory)

	var r0 []moderators.Domain
	if rf, ok := ret.Get(0).(func(context.Context, string) []moderators.Domain); ok {
		r0 = rf(ctx, idCategory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]moderators.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idCategory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
