// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	context "context"
	user "disspace/business/user"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, username, data
func (_m *UseCase) ChangePassword(ctx context.Context, username string, data user.UserDomain) error {
	ret := _m.Called(ctx, username, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, user.UserDomain) error); ok {
		r0 = rf(ctx, username, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Follow provides a mock function with given fields: ctx, username, targetUsername
func (_m *UseCase) Follow(ctx context.Context, username string, targetUsername string) error {
	ret := _m.Called(ctx, username, targetUsername)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, targetUsername)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetModerators provides a mock function with given fields: ctx, idCategory
func (_m *UseCase) GetModerators(ctx context.Context, idCategory string) ([]user.UserProfileDomain, error) {
	ret := _m.Called(ctx, idCategory)

	var r0 []user.UserProfileDomain
	if rf, ok := ret.Get(0).(func(context.Context, string) []user.UserProfileDomain); ok {
		r0 = rf(ctx, idCategory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserProfileDomain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, idCategory)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTop5User provides a mock function with given fields: ctx
func (_m *UseCase) GetTop5User(ctx context.Context) ([]user.UserProfileDomain, error) {
	ret := _m.Called(ctx)

	var r0 []user.UserProfileDomain
	if rf, ok := ret.Get(0).(func(context.Context) []user.UserProfileDomain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserProfileDomain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, id, usernamePayload
func (_m *UseCase) GetUserByID(ctx context.Context, id string, usernamePayload string) (user.UserDomain, error) {
	ret := _m.Called(ctx, id, usernamePayload)

	var r0 user.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) user.UserDomain); ok {
		r0 = rf(ctx, id, usernamePayload)
	} else {
		r0 = ret.Get(0).(user.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, usernamePayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: ctx, username, usernamePayload
func (_m *UseCase) GetUserByUsername(ctx context.Context, username string, usernamePayload string) (user.UserDomain, error) {
	ret := _m.Called(ctx, username, usernamePayload)

	var r0 user.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) user.UserDomain); ok {
		r0 = rf(ctx, username, usernamePayload)
	} else {
		r0 = ret.Get(0).(user.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, usernamePayload)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *UseCase) Login(ctx context.Context, username string, password string) (user.UserSessionDomain, error) {
	ret := _m.Called(ctx, username, password)

	var r0 user.UserSessionDomain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) user.UserSessionDomain); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(user.UserSessionDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, dataSession
func (_m *UseCase) Logout(ctx context.Context, dataSession user.UserSessionDomain) error {
	ret := _m.Called(ctx, dataSession)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, user.UserSessionDomain) error); ok {
		r0 = rf(ctx, dataSession)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, data
func (_m *UseCase) Register(ctx context.Context, data *user.UserDomain) (user.UserDomain, error) {
	ret := _m.Called(ctx, data)

	var r0 user.UserDomain
	if rf, ok := ret.Get(0).(func(context.Context, *user.UserDomain) user.UserDomain); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(user.UserDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *user.UserDomain) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, q, sort
func (_m *UseCase) Search(ctx context.Context, q string, sort string) ([]user.UserProfileDomain, error) {
	ret := _m.Called(ctx, q, sort)

	var r0 []user.UserProfileDomain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []user.UserProfileDomain); ok {
		r0 = rf(ctx, q, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.UserProfileDomain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, q, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unfollow provides a mock function with given fields: ctx, username, targetUsername
func (_m *UseCase) Unfollow(ctx context.Context, username string, targetUsername string) error {
	ret := _m.Called(ctx, username, targetUsername)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, username, targetUsername)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserInfo provides a mock function with given fields: ctx, username, data
func (_m *UseCase) UpdateUserInfo(ctx context.Context, username string, data user.UserDomain) error {
	ret := _m.Called(ctx, username, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, user.UserDomain) error); ok {
		r0 = rf(ctx, username, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserProfile provides a mock function with given fields: ctx, username, data
func (_m *UseCase) UpdateUserProfile(ctx context.Context, username string, data user.UserProfileDomain) error {
	ret := _m.Called(ctx, username, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, user.UserProfileDomain) error); ok {
		r0 = rf(ctx, username, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProfileGetByUsername provides a mock function with given fields: ctx, username
func (_m *UseCase) UserProfileGetByUsername(ctx context.Context, username string) (user.UserProfileDomain, error) {
	ret := _m.Called(ctx, username)

	var r0 user.UserProfileDomain
	if rf, ok := ret.Get(0).(func(context.Context, string) user.UserProfileDomain); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(user.UserProfileDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
